### ISSUE TITLE
request for map used in PapArt

### ISSUE THREAD

**Issue by Elhamkr** [graphcore/popart#7]
Is there a license for the map used in the geographical distribution of PapArt?
What is the exact source of the map used in the PopArt network?

I require permission from an open-access journal to publish under the Creative Commons Attribution License (CCAL) CC BY 4.0 (http://creativecommons.org/licenses/by/4.0/).

They don't accept the copyright of the image.

**Comment by ManueleSigona** [comment]
Hi @Elhamkr,

I believe you're referring to the popart in https://github.com/jessicawleigh/popart, rather than the one here from Graphcore: https://github.com/graphcore/popart. Specifically, it seems to me that the map you mention is the one in this paper: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12410.

Please correct me if I'm wrong. But assuming that my guess is correct I'm going to close the 3 issues you opened here on the Graphcore's PopART, as they refer to another repository with the same name.

Manuele,
Graphcore

**Comment by markkgc** [comment]
Closing issue as it refers to another repository with the same name.

**Comment by markkgc** [comment]
Closing issue as it refers to another repository with the same name.

**Comment by Elhamkr** [comment]
> Hi @Elhamkr,
> 
> I believe you're referring to the popart in https://github.com/jessicawleigh/popart, rather than the one here from Graphcore: https://github.com/graphcore/popart. Specifically, it seems to me that the map you mention is the one in this paper: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12410.
> 
> Please correct me if I'm wrong. But assuming that my guess is correct I'm going to close the 3 issues you opened here on the Graphcore's PopART, as they refer to another repository with the same name.
> 
> Manuele, Graphcore

Dear Manuele,
Defenetitly I mean the world map in the PopArt. The journal asks me for the license and permission to copywriting, but I can't find any site such as GIS,...NASA.. or any valid source in that article and in the site of apart, I ask the funder if that can help me to find the license.
Thanks
